# -*- coding: utf-8 -*-
"""SICRO_COMPLETO_2022-2024 - VEÍCULO RODOFERROVIÁRIO

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_IcdcP9mLREEp3wOduhzXz2OQHIm8VJ6
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

df = pd.read_excel("SICRO_COMPLETO_2022-2024.xlsx")
df = df.dropna()
df

pd.set_option('display.float_format', '{:,.2f}'.format)

"""### ANÁLISE DA FAMÍLIA **VEÍCULO RODOFERROVIÁRIO** SICRO 2022-2024 **(data1)** :

- HÁ 2 CATEGORIAS NA COLUNA **DESCRIÇÕES** DOS VEÍCULOS RODOVIÁRIOS:

1.   **carro** -  Carro controle ferroviário - 186 kW
2.  **veiculo** - Veículo ferroviário para capina química com capacidade de 12.000 l - 115 kW

- HÁ 3 CATEGORIAS NA COLUNA **PEI** DOS VEÍCULOS RODOVIÁRIOS:

1. **EST** - O equipamento está parado, sem uso produtivo. Pode incorrer em custos de posse.
2. **DMT** - O equipamento está em movimento, mas sem executar a tarefa produtiva (por exemplo, indo até o local da obra).
3. **P** - O equipamento está operando ativamente, executando sua função principal (ex: carregando, escavando etc.).






"""



data1 = df[df["Família"] == "VEÍCULO RODOFERROVIÁRIO"]
data1
carro = data1[data1["DESCRIÇÃO"] == 'Carro controle ferroviário - 186 kW']
veiculo = data1[data1["DESCRIÇÃO"] == 'Veículo ferroviário para capina química com capacidade de 12.000 l - 115 kW']
data1["Preço.Final"] = pd.to_numeric(data1["Preço.Final"])
data1["Preço.Entregue"]  = pd.to_numeric(data1["Preço.Entregue"])
carro["Preço.Final"] = pd.to_numeric(carro["Preço.Final"])
veiculo["Preço.Final"] = pd.to_numeric(veiculo["Preço.Final"])

"""**data1 = FAMÍLIA DE VEÍCULO RODOFERROVIÁRIO COMPLETA**

**carro -  CATEGORIA DE VEÍCULO RODOFERROVIÁRIO - "Carro controle ferroviário - 186 kW"**
"""

data1["DESCRIÇÃO"].unique()

data1["PEI"].unique()

carro

"""**veiculo -  CATEGORIA DE VEÍCULO RODOFERROVIÁRIO - "Veículo ferroviário para capina química com capacidade de 12.000 l - 115 kW"**"""

veiculo

"""### **SEMESTRES DE 2022 - 2024(data1) :** *PREÇO FINAL MÉDIO*"""

df_year = data1.groupby("REF")["Preço.Final"].mean().reset_index()

plt.figure(figsize=(6, 4))
sns.lineplot(
    data=df_year,
    x="REF",
    y="Preço.Final",
    marker="o",
    color="crimson"
)

plt.title("Preço FINAL por semestre 2022-2024 - DATA 1")
plt.xlabel("MESES")
plt.ylabel("Preço FINAL (R$)")
plt.show()

"""### **SEMESTRES DE 2022 - 2024 (carro) :** *PREÇO FINAL MÉDIO*"""

df_year =carro.groupby("REF")["Preço.Final"].mean().reset_index()

plt.figure(figsize=(6, 4))
sns.lineplot(
    data=df_year,
    x="REF",
    y="Preço.Final",
    marker="o",
    color="crimson"
)

plt.title("Preço FINAL por semestre 2022-2024 - CARRO")
plt.xlabel("MESES")
plt.ylabel("Preço FINAL (R$)")
plt.show()

"""### **SEMESTRES DE 2022 - 2024 (veiculo) :** *PREÇO FINAL MÉDIO*"""

df_year = veiculo.groupby("REF")["Preço.Final"].mean().reset_index()

plt.figure(figsize=(6, 4))
sns.lineplot(
    data=df_year,
    x="REF",
    y="Preço.Final",
    marker="o",
    color="crimson"
)

plt.title("Preço FINAL por semestre 2022-2024 - VEÍCULO")
plt.xlabel("MESES")
plt.ylabel("Preço FINAL (R$)")
plt.show()

"""### **ANÁLISE:**


1.   Apesar de carro e veículos terem a mesma quantidade na contagem final de Veículos RODOFERRIVIÃRIOS, houve uma queda maior na MD do preço final de carros, no primeiro semestre de 2023, em relação a MD de preço final de veículo.
2. Em todas as categorias, houve um aumento brusco na média do preço final de 2022 até 2023, e depois de então os preços se mantiveram mais estáveis, o que pode estar relacionado à mudança de governo e novos investimentos no setor.

### **SOMA DO PREÇO FINAL POR TIPO DE PEI** DA FAMÍLIA VEÍCULO RODOFERROVIÁRIO (data1)
"""

data1.groupby("PEI")["Preço.Final"].sum().sort_values(ascending=False)

plt.figure(figsize=(6,4))
sns.barplot(
data = data1[data1["Família"] == "VEÍCULO RODOFERROVIÁRIO"],
x = "PEI",
y = "Preço.Final",
color="crimson",
estimator = "sum")
plt.title("SOMA DOS TIPO DE PEI DA FAMÍLIA - VEÍCULO RODOFERROVIÁRIO")
plt.xlabel("TIPO DE PEI")
plt.ylabel("PREÇO MÉDIO")
plt.show()

"""## **ANÁLISE:**

O valor da SOMA do preço final por tipo de PEI mostra que os equipamentos parados gastam 6x mais do que os equipamentos que estão em produção em todo Brasil SOMENTE dos VEÍCULO RODOFERROVIÁRIO entre 2022 e 2024

### **HISTOGRAMAS DE " PREÇO FINAL" DA FAMIÍLIA VEÍCULO RODOFERROVIÁRIO POR CADA TIPO DE PEI**
"""

plt.figure(figsize=(6, 4))
sns.histplot(
    data1[data1["PEI"] == "EST"]["Preço.Final"],
    bins=20,
    kde=False,
    color="crimson"
)

plt.title("Histograma de preços VEÍCULO RODOFERROVIÁRIO por PEI - EST")
plt.xlabel("Preço ")
plt.ylabel("Frequência")
plt.show()

plt.figure(figsize=(6, 4))
sns.histplot(
    data1[data1["PEI"] == "DMT"]["Preço.Final"],
    bins=20,
    kde=False,
    color="crimson"
)

plt.title("Histograma de preços VEÍCULO RODOFERROVIÁRIO por PEI - DMT")
plt.xlabel("Preço ")
plt.ylabel("Frequência")
plt.show()

"""### **HISTOGRAMAS DE " PREÇO FINAL" DA FAMIÍLIA VEÍCULO RODOFERROVIÁRIO POR CADA TIPO DE PEI**"""

plt.figure(figsize=(6, 4))
sns.histplot(
    data1[data1["PEI"] == "P"]["Preço.Final"],
    bins=20,
    kde=False,
    color="crimson"
)

plt.title("Histograma de preços VEÍCULO RODOFERROVIÁRIO por PEI - P")
plt.xlabel("Preço ")
plt.ylabel("Frequência")
plt.show()

"""## **ANÁLISE:**

Os histogramas de preço final dos veículos RODOFERROVIÁRIOS, segmentados por tipo de PEI (DMT, EST e P), indicam que a maior parte dos veículos possui preços concentrados em faixas mais baixas.
Existem outliers em todas as categorias, mas com poucos registros mostrando preços muito acima.

### **QUANTIDADE DE DISTRUIBIÇÃO DE PEI DE VEÍCULO RODOFERROVIÁRIO (DMT, EST, P)**
"""

dataCOUNT = data1.loc[:,["PEI", "Preço.Final", 'Preço.Entregue']]
dataCOUNT.groupby('PEI').count().sort_values(by='Preço.Final', ascending=False).head(3)

"""### ***ANÁLISES ADICIONAIS:***

### **5 MAIORES MÉDIAS NO PREÇO ENTREGUE E PREÇO FINAL POR UF**
"""

dfValues = data1.loc[:,["UF", "Preço.Final", 'Preço.Entregue']]
dfValues.groupby('UF').mean().sort_values(by='Preço.Final', ascending=False).head(5)

"""### **5 MAIORES MEDIANAS NO PREÇO ENTREGUE E PREÇO FINAL POR UF**"""

dfValues = data1.loc[:,["UF", "Preço.Final", 'Preço.Entregue']]
dfValues.groupby('UF').median().sort_values(by='Preço.Final', ascending=False).head(3)

"""### **5 MAIORES SOMAS NO PREÇO ENTREGUE E PREÇO FINAL POR UF**"""

dataCOUNT = data1.loc[:,["UF", "Preço.Final", 'Preço.Entregue']]
dataCOUNT.groupby('UF').sum().sort_values(by='Preço.Final', ascending=False).head(5)

"""### **SOMA DO TOTAL DO PREÇO FINAL**"""

data1["Preço.Final"].sum()

"""### **MÉDIA TOTAL DO PREÇO FINAL**"""

data1["Preço.Entregue"].mean()

"""### **XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX**

### **ANALISE DE VEÍCULO RODOFERROVIÁRIO**: ESCOLHA UMA UF ->
Depois clique em EXECUTAR TUDO.
"""

uf = input("ESCOLHA UMA UF: ").upper()
data = data1[df["UF"] == uf]

"""### **XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX**"""

data.drop_duplicates()
data["Preço.Final"] = pd.to_numeric(data["Preço.Final"])
data["Preço.Entregue"]  = pd.to_numeric(data["Preço.Entregue"])

data

data.describe()

"""**QUANTIDADE DE DISTRUIBIÇÃO DE PEI DE VEÍCULO RODOFERROVIÁRIO (DMT, EST, P)** *UF ESCOLHIDA*"""

dataCOUNT = data.loc[:,["PEI", "Preço.Final", 'Preço.Entregue']]
dataCOUNT.groupby('PEI').count().sort_values(by='Preço.Final', ascending=False).head(3)

"""### **SOMA DO TOTAL DO PREÇO FINAL** *UF ESCOLHIDA*"""

data["Preço.Final"].sum()

"""### **MÉDIA DO TOTAL DO PREÇO FINAL** *UF ESCOLHIDA*"""

data["Preço.Final"].mean()

"""### **SEMESTRES DE 2022 - 2024 DA UF ESCOLHIDA :** *PREÇO FINAL MÉDIO*"""

df_year = data.groupby("REF")["Preço.Final"].mean().reset_index()

plt.figure(figsize=(6, 4))
sns.lineplot(
    data=df_year,
    x="REF",
    y="Preço.Final",
    marker="o",
    color="crimson"
)

plt.title("Preço FINAL por semestre 2022-2024 - uf escolhida")
plt.xlabel("MESES")
plt.ylabel("Preço FINAL (R$)")
plt.show()

"""### ***MÉDIA DO PREÇO FINAL E PREÇO ENTREGUE DA UF ESCOLHIDA***"""

dfValues = data.loc[:,["PEI", "Preço.Final", 'Preço.Entregue']]
dfValues.groupby('PEI').mean()

"""### ***MEDIANA DO PREÇO FINAL E PREÇO ENTREGUE DA UF ESCOLHIDA***"""

dfValues = data.loc[:,["PEI", "Preço.Final", 'Preço.Entregue']]
dfValues.groupby('PEI').median()

"""### ***MODA DO TIPO DE PEI MAIS USADO DA UF ESCOLHIDA***"""

data["PEI"].mode()

"""### ***MÉDIA DE PREÇO FINAL POR TIPO DE PEI DA UF ESCOLHIDA***"""

dataCOUNT = data.loc[:,["PEI", "Preço.Final", 'Preço.Entregue']]
dataCOUNT.groupby('PEI').mean().sort_values(by='Preço.Final', ascending=False).head(3)

"""### ***Preço Final MÉDIO por TIPO DE PEI na UF selecionada***"""

plt.figure(figsize=(6,4))
sns.barplot(
data = data[data["Família"] == "VEÍCULO RODOFERROVIÁRIO"],
x = "PEI",
y = "Preço.Final",
color="crimson",
estimator = "mean")
plt.title("Preço Final MÉDIO por TIPO DE PEI na UF selecionada")
plt.xlabel("TIPO DE PEI")
plt.ylabel("PREÇO MÉDIO")
plt.show()